# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asy_var_vus_c <- function(tt, D_hat, mu_hat, EstFunc, Hess_inv, Der_D1_hat, Der_D2_hat, Der_D3_hat) {
    .Call(`_bcROCsurface_asy_var_vus_c`, tt, D_hat, mu_hat, EstFunc, Hess_inv, Der_D1_hat, Der_D2_hat, Der_D3_hat)
}

vus_c <- function(tt, dd) {
    .Call(`_bcROCsurface_vus_c`, tt, dd)
}

vus_c_full <- function(tt1, tt2, tt3) {
    .Call(`_bcROCsurface_vus_c_full`, tt1, tt2, tt3)
}

vus_c_full_core <- function(tt1, tt2, tt3) {
    .Call(`_bcROCsurface_vus_c_full_core`, tt1, tt2, tt3)
}

