# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asyVarVUS_C <- function(tt, D_hat, mu_hat, EstFunc, Hess_inv, Der_D1_hat, Der_D2_hat, Der_D3_hat) {
    .Call('bcROCsurface_asyVarVUS_C', PACKAGE = 'bcROCsurface', tt, D_hat, mu_hat, EstFunc, Hess_inv, Der_D1_hat, Der_D2_hat, Der_D3_hat)
}

vusC <- function(tt, dd) {
    .Call('bcROCsurface_vusC', PACKAGE = 'bcROCsurface', tt, dd)
}

